// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// reassign
int reassign(NumericVector x, List center);
RcppExport SEXP _DataStreamClustering_reassign(SEXP xSEXP, SEXP centerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type center(centerSEXP);
    rcpp_result_gen = Rcpp::wrap(reassign(x, center));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_yada();
RcppExport SEXP _rcpp_module_boot_MOD_HCM();
RcppExport SEXP _rcpp_module_boot_MOD_Mudi();

static const R_CallMethodDef CallEntries[] = {
    {"_DataStreamClustering_reassign", (DL_FUNC) &_DataStreamClustering_reassign, 2},
    {"_rcpp_module_boot_yada", (DL_FUNC) &_rcpp_module_boot_yada, 0},
    {"_rcpp_module_boot_MOD_HCM", (DL_FUNC) &_rcpp_module_boot_MOD_HCM, 0},
    {"_rcpp_module_boot_MOD_Mudi", (DL_FUNC) &_rcpp_module_boot_MOD_Mudi, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_DataStreamClustering(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
